### ISSUE TITLE
Need to manually execute "node server.js" to start the server

### ISSUE THREAD

**Issue by muddro1** [ferdium/ferdium-server#60]
Not sure what is happening, Running ferdium for a while without issue, no changes to my docker compose or anything. But recently, when trying to run the container, the logs show it goes through all its steps, up to and including an APP_KEY and finished with "Nothing to migrate". Then it stops, and cannot access the ferdium server or the website it is supposed to generate. 

I then exec'd into the container and ran node server.js and it fixed it and started listening on the given port, and all worked. However, not sure why it is not automatically running server.js.

**Comment by SpecialAro** [comment]
> Not sure what is happening, Running ferdium for a while without issue, no changes to my docker compose or anything. But recently, when trying to run the container, the logs show it goes through all its steps, up to and including an APP_KEY and finished with "Nothing to migrate". Then it stops, and cannot access the ferdium server or the website it is supposed to generate.
> 
> I then exec'd into the container and ran node server.js and it fixed it and started listening on the given port, and all worked. However, not sure why it is not automatically running server.js.

Hi @muddro1 !

Have you tried to wait a bit (like 10 min or so, maximum and depending on your hardware specs) ?

I've faced this issue as well and I think I might have fix it for the upcoming v2 of the Ferdium Server https://github.com/ferdium/ferdium-server/pull/47

The culprit is in this line https://github.com/ferdium/ferdium-server/pull/47/commits/1a39e47679b8460a998e14554aca4f64c78b9da5#diff-4f5cabe26761257a4d685a6edc7a43e0fe0f78762f50eeb48530f2bd3b3ee7caL67 that takes too long to execute (as it is changing the ownership and group of every file and folder in the project.
